sudo: required
services:
  - docker


before install:
  - docker build -t ce318002/multicontainer -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ce318002/multicontainer npm test

after_success:
  - docker build -t ce318002/multi-client ./client
  - docker build -t ce318002/multi-nginx ./nginx
  - docker build -t ce318002/multi-server ./server
  - docker build -t ce318002/multi-worker ./worker
#login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push to docker hub
  - docker push ce318002/multi-client
  - docker push ce318002/multi-nginx
  - docker push ce318002/multi-server
  - docker push ce318002/multi-worker


